# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/martin/Projects/AvgLib

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/martin/Projects/AvgLib

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/martin/Projects/AvgLib/CMakeFiles /home/martin/Projects/AvgLib/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/martin/Projects/AvgLib/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named AvgLib

# Build rule for target.
AvgLib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AvgLib
.PHONY : AvgLib

# fast build rule for target.
AvgLib/fast:
	$(MAKE) -f CMakeFiles/AvgLib.dir/build.make CMakeFiles/AvgLib.dir/build
.PHONY : AvgLib/fast

lib/File.o: lib/File.cpp.o

.PHONY : lib/File.o

# target to build an object file
lib/File.cpp.o:
	$(MAKE) -f CMakeFiles/AvgLib.dir/build.make CMakeFiles/AvgLib.dir/lib/File.cpp.o
.PHONY : lib/File.cpp.o

lib/File.i: lib/File.cpp.i

.PHONY : lib/File.i

# target to preprocess a source file
lib/File.cpp.i:
	$(MAKE) -f CMakeFiles/AvgLib.dir/build.make CMakeFiles/AvgLib.dir/lib/File.cpp.i
.PHONY : lib/File.cpp.i

lib/File.s: lib/File.cpp.s

.PHONY : lib/File.s

# target to generate assembly for a file
lib/File.cpp.s:
	$(MAKE) -f CMakeFiles/AvgLib.dir/build.make CMakeFiles/AvgLib.dir/lib/File.cpp.s
.PHONY : lib/File.cpp.s

lib/Math/vector.o: lib/Math/vector.cpp.o

.PHONY : lib/Math/vector.o

# target to build an object file
lib/Math/vector.cpp.o:
	$(MAKE) -f CMakeFiles/AvgLib.dir/build.make CMakeFiles/AvgLib.dir/lib/Math/vector.cpp.o
.PHONY : lib/Math/vector.cpp.o

lib/Math/vector.i: lib/Math/vector.cpp.i

.PHONY : lib/Math/vector.i

# target to preprocess a source file
lib/Math/vector.cpp.i:
	$(MAKE) -f CMakeFiles/AvgLib.dir/build.make CMakeFiles/AvgLib.dir/lib/Math/vector.cpp.i
.PHONY : lib/Math/vector.cpp.i

lib/Math/vector.s: lib/Math/vector.cpp.s

.PHONY : lib/Math/vector.s

# target to generate assembly for a file
lib/Math/vector.cpp.s:
	$(MAKE) -f CMakeFiles/AvgLib.dir/build.make CMakeFiles/AvgLib.dir/lib/Math/vector.cpp.s
.PHONY : lib/Math/vector.cpp.s

lib/Random/PerlinNoise.o: lib/Random/PerlinNoise.cpp.o

.PHONY : lib/Random/PerlinNoise.o

# target to build an object file
lib/Random/PerlinNoise.cpp.o:
	$(MAKE) -f CMakeFiles/AvgLib.dir/build.make CMakeFiles/AvgLib.dir/lib/Random/PerlinNoise.cpp.o
.PHONY : lib/Random/PerlinNoise.cpp.o

lib/Random/PerlinNoise.i: lib/Random/PerlinNoise.cpp.i

.PHONY : lib/Random/PerlinNoise.i

# target to preprocess a source file
lib/Random/PerlinNoise.cpp.i:
	$(MAKE) -f CMakeFiles/AvgLib.dir/build.make CMakeFiles/AvgLib.dir/lib/Random/PerlinNoise.cpp.i
.PHONY : lib/Random/PerlinNoise.cpp.i

lib/Random/PerlinNoise.s: lib/Random/PerlinNoise.cpp.s

.PHONY : lib/Random/PerlinNoise.s

# target to generate assembly for a file
lib/Random/PerlinNoise.cpp.s:
	$(MAKE) -f CMakeFiles/AvgLib.dir/build.make CMakeFiles/AvgLib.dir/lib/Random/PerlinNoise.cpp.s
.PHONY : lib/Random/PerlinNoise.cpp.s

lib/Random/PermutationTable.o: lib/Random/PermutationTable.cpp.o

.PHONY : lib/Random/PermutationTable.o

# target to build an object file
lib/Random/PermutationTable.cpp.o:
	$(MAKE) -f CMakeFiles/AvgLib.dir/build.make CMakeFiles/AvgLib.dir/lib/Random/PermutationTable.cpp.o
.PHONY : lib/Random/PermutationTable.cpp.o

lib/Random/PermutationTable.i: lib/Random/PermutationTable.cpp.i

.PHONY : lib/Random/PermutationTable.i

# target to preprocess a source file
lib/Random/PermutationTable.cpp.i:
	$(MAKE) -f CMakeFiles/AvgLib.dir/build.make CMakeFiles/AvgLib.dir/lib/Random/PermutationTable.cpp.i
.PHONY : lib/Random/PermutationTable.cpp.i

lib/Random/PermutationTable.s: lib/Random/PermutationTable.cpp.s

.PHONY : lib/Random/PermutationTable.s

# target to generate assembly for a file
lib/Random/PermutationTable.cpp.s:
	$(MAKE) -f CMakeFiles/AvgLib.dir/build.make CMakeFiles/AvgLib.dir/lib/Random/PermutationTable.cpp.s
.PHONY : lib/Random/PermutationTable.cpp.s

lib/Random/VoronoiNoise.o: lib/Random/VoronoiNoise.cpp.o

.PHONY : lib/Random/VoronoiNoise.o

# target to build an object file
lib/Random/VoronoiNoise.cpp.o:
	$(MAKE) -f CMakeFiles/AvgLib.dir/build.make CMakeFiles/AvgLib.dir/lib/Random/VoronoiNoise.cpp.o
.PHONY : lib/Random/VoronoiNoise.cpp.o

lib/Random/VoronoiNoise.i: lib/Random/VoronoiNoise.cpp.i

.PHONY : lib/Random/VoronoiNoise.i

# target to preprocess a source file
lib/Random/VoronoiNoise.cpp.i:
	$(MAKE) -f CMakeFiles/AvgLib.dir/build.make CMakeFiles/AvgLib.dir/lib/Random/VoronoiNoise.cpp.i
.PHONY : lib/Random/VoronoiNoise.cpp.i

lib/Random/VoronoiNoise.s: lib/Random/VoronoiNoise.cpp.s

.PHONY : lib/Random/VoronoiNoise.s

# target to generate assembly for a file
lib/Random/VoronoiNoise.cpp.s:
	$(MAKE) -f CMakeFiles/AvgLib.dir/build.make CMakeFiles/AvgLib.dir/lib/Random/VoronoiNoise.cpp.s
.PHONY : lib/Random/VoronoiNoise.cpp.s

lib/StringLib.o: lib/StringLib.cpp.o

.PHONY : lib/StringLib.o

# target to build an object file
lib/StringLib.cpp.o:
	$(MAKE) -f CMakeFiles/AvgLib.dir/build.make CMakeFiles/AvgLib.dir/lib/StringLib.cpp.o
.PHONY : lib/StringLib.cpp.o

lib/StringLib.i: lib/StringLib.cpp.i

.PHONY : lib/StringLib.i

# target to preprocess a source file
lib/StringLib.cpp.i:
	$(MAKE) -f CMakeFiles/AvgLib.dir/build.make CMakeFiles/AvgLib.dir/lib/StringLib.cpp.i
.PHONY : lib/StringLib.cpp.i

lib/StringLib.s: lib/StringLib.cpp.s

.PHONY : lib/StringLib.s

# target to generate assembly for a file
lib/StringLib.cpp.s:
	$(MAKE) -f CMakeFiles/AvgLib.dir/build.make CMakeFiles/AvgLib.dir/lib/StringLib.cpp.s
.PHONY : lib/StringLib.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... AvgLib"
	@echo "... edit_cache"
	@echo "... lib/File.o"
	@echo "... lib/File.i"
	@echo "... lib/File.s"
	@echo "... lib/Math/vector.o"
	@echo "... lib/Math/vector.i"
	@echo "... lib/Math/vector.s"
	@echo "... lib/Random/PerlinNoise.o"
	@echo "... lib/Random/PerlinNoise.i"
	@echo "... lib/Random/PerlinNoise.s"
	@echo "... lib/Random/PermutationTable.o"
	@echo "... lib/Random/PermutationTable.i"
	@echo "... lib/Random/PermutationTable.s"
	@echo "... lib/Random/VoronoiNoise.o"
	@echo "... lib/Random/VoronoiNoise.i"
	@echo "... lib/Random/VoronoiNoise.s"
	@echo "... lib/StringLib.o"
	@echo "... lib/StringLib.i"
	@echo "... lib/StringLib.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

